const APP_CONSTANTS = {
  WIDTH: 943,
  HEIGHT: 360
}

const MESSAGING_CONSTANTS = {
  ERROR: 'VVG_ERROR',
  MESSAGE: 'VVG_MESSAGE',
  DELETE: 'VVG_DELETE',
  PUSH: 'VVG_PUSH',
  SAVE: 'VVG_SAVE',
  GENERATE: 'VVG_GENERATE',
  UPDATE: 'VVG_UPDATE',
  UPDATED: 'VVG_UPDATED',
  CONFIG: 'VVG_CONFIG'
}

module.exports = {
  APP_CONSTANTS,
  MESSAGING_CONSTANTS
}